name: solwave
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  firebase_auth: ^4.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.8.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  path: ^1.8.3
  path_provider: ^2.1.2
  sembast: ^3.5.0+1
  webview_flutter: ^4.4.4
  solana: ^0.30.1
  bs58: ^1.0.2
  json5: ^0.8.2
  url_launcher: ^6.2.3
  share_plus: ^7.2.1
  uni_links: ^0.5.1
  pinenacl: ^0.5.1
  connectivity_plus: ^5.0.2
  installed_apps: ^1.4.0
  appcheck: ^1.0.6

dev_dependencies:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: lib/fonts/rubik_regular.ttf
        - asset: lib/fonts/rubik_medium.ttf
    - family: Inter
      fonts:
        - asset: lib/fonts/inter_regular.ttf
        - asset: lib/fonts/inter_medium.ttf
    - family: Poppins
      fonts:
        - asset: lib/fonts/poppins_regular.ttf
        - asset: lib/fonts/poppins_medium.ttf

  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
